### PR TITLE
Update CAISO0.1.py

### PR DESCRIPTION
**Pull request by romulus97**
Yufei, see if the pull request tool works. Can you approve it and see what I edited? Just curious. 

I changed the set definition for paths and hurdle rates. I think the hurdles rates are parameters defined over a matrix paths, where paths is zones. zones. 

Still a little confused about the best way to set this up, though.

### CODE REVIEW

**Comment by suyufei** [comment]
I think I can see your edits but those are not highlighted. So it is a little hard to find. Did you put hurdle rate into parameters already? 

There are some highlighted texts in the objective function section. Also for our max capacity constraint, it seems that ^M is added and highlighted. I am not sure what that mean.

**Comment by romulus97** [comment]
Hmm. The edits should show up as green/red highlights. Are you able to merge the pull request?

**Comment by romulus97** [comment]
No, I haven't added the path parameters to the model yet. I'm still setting up the data file (which is going well).

**Comment by suyufei** [comment]
Yap. I think I can. What does merging pull request do?

**Comment by romulus97** [comment]
It means you accept the changes to the code I proposed (which should be highlighted... ). It's a good way to edit the code collaboratively.

________________________________

**Comment by suyufei** [comment]
Awesome. I will work on it more after 9th cos I have a final project on that day,

**Pull request merged**
